server:
  port: 8080
  address: 0.0.0.0
  servlet.session.cookie.http-only: true

spring:
  datasource:
    url: jdbc:h2:file:./xssdemo
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      
logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: WARN
    org.springframework.security.authentication: DEBUG
    sql: DEBUG
    root: WARN